services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 8857:80
        depends_on:
            - app
            - db
            - node
            - redis

    app:
        build:
            context: .
            dockerfile: _docker/app/php.Dockerfile
        volumes:
            - ./:/var/www
        restart: unless-stopped
        environment:
            - TZ=Europe/Moscow

    queue:
        build:
            context: .
            dockerfile: _docker/app/php.Dockerfile
        command: php /var/www/artisan queue:work --tries=3
        volumes:
        - ./:/var/www

    db:
        image: mysql:8.0
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - 8101:3306

    node:
        build:
            context: .
            dockerfile: _docker/nodejs/node.Dockerfile
        tty: true
        ports:
            - "5173:5173"
        volumes:
            - ./:/var/www
    
    composer:
        build:
            context: .
            dockerfile: _docker/composer/composer.Dockerfile
        volumes:
            - ./:/var/www

    artisan:
        build:
            context: .
            dockerfile: _docker/app/php.Dockerfile
        volumes:
            - ./:/var/www
        entrypoint: ["php", "/var/www/artisan"]

    redis:
        image: redis:latest
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        environment:
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_DATABASES=16

    cleanup:
        image: alpine
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: >
            sh -c "docker container prune -f && docker image prune -f"
            
volumes:
    redis_data: