version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        container_name: LP_nginx
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
            - node
        networks:
            - my_network
    app:
        build:
            context: .
            dockerfile: _docker/app/php.Dockerfile
            network: host
        container_name: LP_app
        restart: unless-stopped
        volumes:
            - ./:/var/www
        depends_on:
            - db
        networks:
            - my_network
    db:
        image: mysql:8.0
        container_name: LP_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: prod
            SERVICE_NAME: mysql
        ports:
            - 3316:3306
        volumes:
            - ./tmp/db:/var/lib/mysql
        networks:
            - my_network
    node:
        build:
            context: .
            dockerfile: _docker/nodejs/node.Dockerfile
            network: host
        container_name: LP_node
        tty: true
        ports:
            - "80:5173"
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - my_network
networks:
    my_network:
        driver: bridge