version: "3"

services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped
        tty: true
        depends_on:
            - app
        container_name: LP_nginx

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        image: php:8.1
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - ./:/var/www
        depends_on:
            - db
        container_name: LP_app
        networks:
            - app-network

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
            MYSQL_ROOT_PASSWORD: p@$$w0rd
        ports:
            - 3306:3306
        tty: true
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: LP_db
        networks:
            - app-network

    node:
        build:
            context: .
            dockerfile: _docker/nodejs/Dockerfile
        tty: true
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - app
        container_name: LP_node
    networks:
        app-network:
            driver: bridge
