version: "3"
services:
    networks:
        personalPage:
            driver: bridge
    app:
        build:
            args:
                user: ilia
                uid: 1000
            context: .
            dockerfile: _docker/app/Dockerfile
        image: personalPage
        container_name: LP_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - personalPage
    db:
        image: mysql:8.0
        container_name: LP_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: prod
            SERVICE_NAME: mysql
        volumes:
            - ./tmp/db:/var/lib/mysql
        networks:
            - personalPage
    nginx:
        image: nginx:latest
        container_name: LP_nginx
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
        networks:
            - personalPage
    node:
        build:
            context: .
            dockerfile: _docker/nodejs/Dockerfile
        container_name: LP_node
        tty: true
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - personalPage
