version: "3"
services:
    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
            network: host
        container_name: LP_app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - db
        network_mode: "host"
    db:
        image: mysql:8.0
        container_name: LP_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: prod
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        volumes:
            - ./tmp/db:/var/lib/mysql
        network_mode: "host"
    nginx:
        image: nginx:latest
        container_name: LP_nginx
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
        network_mode: "host"
    node:
        build:
            context: .
            dockerfile: _docker/nodejs/Dockerfile
            network: host
        container_name: LP_node
        tty: true
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - ./:/var/www
        depends_on:
            - app
        network_mode: "host"
